
vscode:
  extensions:
    - ms-python.python
ports:
  - port: 3002
    onOpen: ignore
    visibility: private
  - port: 3005
    onOpen: ignore
    visibility: private
tasks:
  - name: Install Deps
    init: |
      pip install -r dev-requirements.txt
      pip install -e .
  - name: Pull and setup env
    command: |
      git pull &&
      source scripts/aliases.sh
