
vscode:
  extensions:
    - ms-python.python
ports:
  - port: 3002
    onOpen: ignore
    visibility: private
  - port: 3005
    onOpen: ignore
    visibility: private
tasks:
- command: >
    pip install -r dev-requirements.txt \
    && pip install -e . \
    && source scripts/aliases.sh